import './registration.spec.cy.js'
import './login.spec.cy.js'
import './add_customer.spec.cy'
import './add_contacts.spec.cy'
import './add_vendor.spec.cy'
import './add_attributes.spec.cy'
import './create_category.spec.cy'
import './create_newProduct.spec.cy'
import './Accounting/invoice.spec.cy'
import './Accounting/create_approved_invoices.spec.cy'
import './Accounting/create_draft_bill.spce.cy'
import './Accounting/create_approved_bill.spce.cy'

